name: gpm
version: 0.2.2
description:
  An easy command-line tool for testing and building monorepos (multi-package repositories).
homepage: https://github.com/dint-dev/gpm
executables:
  gpm:

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  args: ^2.0.0
  boolean_selector: ^2.1.0
  meta: ^1.3.0-nullsafety.6
  yaml: ^3.1.0


dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
