name: gpm
version: 0.1.0
description:
  GPM (Green Package Manager) is a package management and scripting tool for multi-package projects.
homepage: https://github.com/dint-dev/gpm
executables:
  gpm:

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  args: ^1.4.0
  boolean_selector: ^2.0.0
  yaml: ^2.0.0

dev_dependencies:
  meta: ^1.1.0
  pedantic: ^1.9.0
  test: ^1.10.0