name: gpm
version: 0.2.1
description:
  GPM is a command-line tool for working with Dart/Flutter repositories. Eases local testing,
  building, and CI setup.
homepage: https://github.com/dint-dev/gpm
executables:
  gpm:

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  args: ^1.4.0
  boolean_selector: ^2.0.0
  meta: ^1.1.0
  yaml: ^2.0.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.10.0